version: "3"
services:
   polydata-sorage-mongodb-web:
     hostname: polydata-sorage-mongodb
     build: .
     healthcheck:
       test: ["CMD", "curl", "localhost:8081/health"]
       interval: 30s
       timeout: 3s
       retries: 60
     ports:
       - "8080:8080"
     environment:
      - polydata.mongodb=mongodb://devdb/polydata21-webapp?readOnly=true&readPreference=secondary
      - JAVA_OPTS=-Xmx512m

